// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package model // import "github.com/saichler/syncit/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Files                []*File  `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_04dd0e6fc2aa6f45, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *File) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "file.File")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_04dd0e6fc2aa6f45) }

var fileDescriptor_file_04dd0e6fc2aa6f45 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8e, 0x31, 0xae, 0xc2, 0x30,
	0x0c, 0x40, 0xd5, 0xdf, 0xf4, 0x4b, 0x98, 0x2d, 0x53, 0xc6, 0xa8, 0x53, 0xa7, 0x56, 0x82, 0x1b,
	0x30, 0x70, 0x80, 0x8e, 0x6c, 0x69, 0x6a, 0x88, 0xa5, 0xa4, 0x41, 0x4d, 0x90, 0x80, 0xd3, 0x23,
	0x27, 0xdb, 0xd3, 0xb3, 0xec, 0x67, 0x80, 0x3b, 0x79, 0x1c, 0x9f, 0x7b, 0xcc, 0x51, 0x0a, 0xe6,
	0xfe, 0x0d, 0xe2, 0x4a, 0x1e, 0xa5, 0x04, 0xb1, 0x99, 0x80, 0xaa, 0xd1, 0xcd, 0x70, 0x98, 0x0b,
	0xb3, 0x4b, 0xf4, 0x45, 0xf5, 0xa7, 0x9b, 0xa1, 0x9d, 0x0b, 0xb3, 0x5b, 0x4d, 0x46, 0xd5, 0x56,
	0xc7, 0xcc, 0xce, 0x99, 0xe4, 0x94, 0xa8, 0xbb, 0xcc, 0x52, 0x43, 0xc7, 0xf7, 0x93, 0xea, 0x74,
	0x3b, 0x1c, 0x4f, 0x30, 0x96, 0x32, 0xa7, 0xe6, 0x3a, 0xb8, 0xf4, 0x37, 0xfd, 0xa0, 0xec, 0x5e,
	0xcb, 0x68, 0x63, 0x98, 0x92, 0x21, 0xeb, 0x3c, 0xee, 0x53, 0xfa, 0x6c, 0x96, 0xf2, 0x14, 0xe2,
	0x8a, 0x7e, 0xf9, 0x2f, 0xaf, 0x9e, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x52, 0x44, 0x10,
	0xb8, 0x00, 0x00, 0x00,
}
