// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package model // import "github.com/saichler/syncit/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Files                []*File  `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_9d6c69ed6c7845ec, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *File) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type Command struct {
	Cli                  string   `protobuf:"bytes,1,opt,name=cli,proto3" json:"cli,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Response             []byte   `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_9d6c69ed6c7845ec, []int{1}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCli() string {
	if m != nil {
		return m.Cli
	}
	return ""
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Command) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "file.File")
	proto.RegisterType((*Command)(nil), "file.Command")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_9d6c69ed6c7845ec) }

var fileDescriptor_file_9d6c69ed6c7845ec = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0x47, 0xe9, 0x4b, 0x9f, 0x7f, 0xae, 0x0e, 0x92, 0x29, 0x38, 0x85, 0x4e, 0x9d, 0x5a, 0xd0,
	0x6f, 0xa0, 0xe0, 0xe2, 0xd6, 0xd1, 0x2d, 0xaf, 0xbd, 0xbe, 0x04, 0xf2, 0xa7, 0xe4, 0x46, 0x50,
	0x3f, 0xbd, 0xdc, 0x44, 0xde, 0x76, 0x72, 0x42, 0x7e, 0x87, 0x00, 0x7c, 0x3a, 0x8f, 0xd3, 0x9e,
	0x53, 0x49, 0xb2, 0x67, 0x1e, 0xbe, 0xa1, 0x7f, 0x73, 0x1e, 0xa5, 0x84, 0x3e, 0x9a, 0x80, 0xaa,
	0xd3, 0xdd, 0x78, 0xbb, 0x54, 0x66, 0x47, 0xee, 0x17, 0xd5, 0x41, 0x77, 0xa3, 0x58, 0x2a, 0xb3,
	0xdb, 0x4c, 0x41, 0x25, 0x9a, 0x63, 0x66, 0x67, 0x0d, 0x59, 0xd5, 0xb7, 0xb7, 0xcc, 0x52, 0xc3,
	0x91, 0xf7, 0x49, 0x1d, 0xb5, 0x18, 0xef, 0x9e, 0x60, 0xaa, 0x65, 0x4e, 0x2d, 0xed, 0x62, 0x78,
	0x87, 0xeb, 0xd7, 0x14, 0x82, 0x89, 0x9b, 0x7c, 0x00, 0xb1, 0x7a, 0xf7, 0xdf, 0x66, 0xe4, 0x49,
	0x93, 0xcf, 0xa4, 0x0e, 0x5a, 0xf0, 0x24, 0xb3, 0x7c, 0x84, 0x9b, 0x8c, 0xb4, 0xa7, 0x48, 0x2d,
	0x7f, 0xbf, 0x5c, 0xce, 0x2f, 0xc3, 0x87, 0x3e, 0xbb, 0x62, 0xbf, 0x4e, 0xd3, 0x9a, 0xc2, 0x4c,
	0xc6, 0xad, 0xd6, 0x63, 0x9e, 0xe9, 0x27, 0xae, 0xae, 0xcc, 0x21, 0x6d, 0xe8, 0x4f, 0x57, 0xf5,
	0xdf, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xdc, 0xd8, 0xf4, 0x05, 0x01, 0x00, 0x00,
}
