// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package model // import "github.com/saichler/syncit/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	NameA                string   `protobuf:"bytes,1,opt,name=nameA,proto3" json:"nameA,omitempty"`
	SizeA                int64    `protobuf:"varint,2,opt,name=sizeA,proto3" json:"sizeA,omitempty"`
	DateA                int64    `protobuf:"varint,3,opt,name=dateA,proto3" json:"dateA,omitempty"`
	HashA                string   `protobuf:"bytes,4,opt,name=hashA,proto3" json:"hashA,omitempty"`
	NameZ                string   `protobuf:"bytes,5,opt,name=nameZ,proto3" json:"nameZ,omitempty"`
	SizeZ                int64    `protobuf:"varint,6,opt,name=sizeZ,proto3" json:"sizeZ,omitempty"`
	DateZ                int64    `protobuf:"varint,7,opt,name=dateZ,proto3" json:"dateZ,omitempty"`
	HashZ                string   `protobuf:"bytes,8,opt,name=hashZ,proto3" json:"hashZ,omitempty"`
	Files                []*File  `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_1e89e6e9858af416, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetNameA() string {
	if m != nil {
		return m.NameA
	}
	return ""
}

func (m *File) GetSizeA() int64 {
	if m != nil {
		return m.SizeA
	}
	return 0
}

func (m *File) GetDateA() int64 {
	if m != nil {
		return m.DateA
	}
	return 0
}

func (m *File) GetHashA() string {
	if m != nil {
		return m.HashA
	}
	return ""
}

func (m *File) GetNameZ() string {
	if m != nil {
		return m.NameZ
	}
	return ""
}

func (m *File) GetSizeZ() int64 {
	if m != nil {
		return m.SizeZ
	}
	return 0
}

func (m *File) GetDateZ() int64 {
	if m != nil {
		return m.DateZ
	}
	return 0
}

func (m *File) GetHashZ() string {
	if m != nil {
		return m.HashZ
	}
	return ""
}

func (m *File) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type Command struct {
	Cli                  string   `protobuf:"bytes,1,opt,name=cli,proto3" json:"cli,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Response             []byte   `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ResponseId           int32    `protobuf:"varint,5,opt,name=responseId,proto3" json:"responseId,omitempty"`
	ResponseCount        int32    `protobuf:"varint,6,opt,name=responseCount,proto3" json:"responseCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_1e89e6e9858af416, []int{1}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCli() string {
	if m != nil {
		return m.Cli
	}
	return ""
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Command) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetResponseId() int32 {
	if m != nil {
		return m.ResponseId
	}
	return 0
}

func (m *Command) GetResponseCount() int32 {
	if m != nil {
		return m.ResponseCount
	}
	return 0
}

func init() {
	proto.RegisterType((*File)(nil), "file.File")
	proto.RegisterType((*Command)(nil), "file.Command")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_1e89e6e9858af416) }

var fileDescriptor_file_1e89e6e9858af416 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0x47, 0xe9, 0xbf, 0x99, 0xe9, 0xfd, 0x3e, 0x45, 0x82, 0x8b, 0x8b, 0x0b, 0x09, 0xc5, 0x45,
	0x57, 0x2d, 0xe8, 0x13, 0xd4, 0x01, 0xc1, 0x6d, 0x96, 0xd9, 0x65, 0x9a, 0x38, 0x0d, 0xb4, 0xcd,
	0xd0, 0x74, 0x16, 0xfa, 0x36, 0xbe, 0x95, 0x8f, 0x23, 0x49, 0x27, 0x56, 0x77, 0xf7, 0x77, 0x02,
	0x07, 0x0e, 0x01, 0x78, 0xd3, 0xbd, 0xaa, 0x4e, 0x93, 0x99, 0x0d, 0x49, 0xdd, 0x5d, 0x7c, 0x45,
	0x90, 0xbe, 0xe8, 0x5e, 0x91, 0x5b, 0xc8, 0x46, 0x31, 0xa8, 0x06, 0x23, 0x1a, 0x95, 0x39, 0x5b,
	0x86, 0xa3, 0x56, 0x7f, 0xa8, 0x06, 0x63, 0x1a, 0x95, 0x09, 0x5b, 0x86, 0xa3, 0x52, 0xcc, 0xaa,
	0xc1, 0x64, 0xa1, 0x7e, 0x38, 0xda, 0x09, 0xdb, 0x35, 0x98, 0x2e, 0x06, 0x3f, 0x82, 0x97, 0x63,
	0xb6, 0x7a, 0x79, 0xf0, 0x72, 0xdc, 0xac, 0x5e, 0x1e, 0xbc, 0x1c, 0xb7, 0xab, 0x97, 0x07, 0x2f,
	0xc7, 0xdd, 0xea, 0xe5, 0x84, 0x42, 0xe6, 0x02, 0x2c, 0xe6, 0x34, 0x29, 0xff, 0x3d, 0x42, 0xe5,
	0xd3, 0x5c, 0x0a, 0x5b, 0x1e, 0x8a, 0xcf, 0x08, 0xb6, 0x7b, 0x33, 0x0c, 0x62, 0x94, 0xe4, 0x06,
	0x92, 0xb6, 0xd7, 0x97, 0x36, 0x77, 0x12, 0x02, 0xa9, 0x98, 0x8e, 0x16, 0x63, 0x9a, 0x94, 0x39,
	0xf3, 0x37, 0xb9, 0x83, 0xdd, 0xa4, 0xec, 0xc9, 0x8c, 0x56, 0xf9, 0xb4, 0xff, 0xec, 0x67, 0x93,
	0x6b, 0x88, 0xb5, 0xbc, 0xa4, 0xc5, 0x5a, 0x92, 0x7b, 0x80, 0xf0, 0xf6, 0x2a, 0x7d, 0x5c, 0xc6,
	0x7e, 0x11, 0xf2, 0x00, 0x57, 0x61, 0xed, 0xcd, 0x79, 0x9c, 0x7d, 0x69, 0xc6, 0xfe, 0xc2, 0xe7,
	0x82, 0xd3, 0xa3, 0x9e, 0xbb, 0xf3, 0xa1, 0x6a, 0xcd, 0x50, 0x5b, 0xa1, 0xdb, 0xae, 0x57, 0x53,
	0x6d, 0xdf, 0xc7, 0x56, 0xcf, 0xf5, 0x60, 0xa4, 0xea, 0x0f, 0x1b, 0xff, 0x5f, 0x4f, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x13, 0x31, 0x72, 0x99, 0xbd, 0x01, 0x00, 0x00,
}
